# -*- coding: utf-8 -*-
"""Survey_Data_Formatter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15x6O5mfYIgkGF4NOsp2ezCM0r-faHb-7
"""

import pandas as pd

# Replace 'survey.csv' with the path to your file
df = pd.read_csv('survey.csv')

# Preview the data
df.head()

def normalize_yes_no(val):
    if str(val).strip().lower() in ['yes', 'y']:
        return 'Yes'
    elif str(val).strip().lower() in ['no', 'n']:
        return 'No'
    else:
        return val

# Apply normalization to all object-type columns
for col in df.select_dtypes(include='object'):
    df[col] = df[col].apply(normalize_yes_no)

# Drop completely empty rows
df.dropna(how='all', inplace=True)

# Drop rows where more than 50% values are missing (optional)
df.dropna(thresh=len(df.columns) // 2, inplace=True)

# Drop columns with all values missing
df.dropna(axis=1, how='all', inplace=True)

# Drop columns with only one unique value
df = df.loc[:, df.nunique() > 1]

df.to_csv('cleaned_survey.csv', index=False)
print("Cleaned survey data saved to 'cleaned_survey.csv'")

import pandas as pd

# Load the cleaned survey data
df = pd.read_csv('cleaned_survey.csv')

# Show first 5 rows
df.head()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('cleaned_survey.csv')

sns.set(style="whitegrid")

#  Bar Chart: Count of Subscribed Responses
plt.figure(figsize=(6, 4))
sns.countplot(x='Subscribed', data=df, palette='pastel')
plt.title('Subscription Status Count')
plt.xlabel('Subscribed')
plt.ylabel('Count')
plt.tight_layout()
plt.show()