# -*- coding: utf-8 -*-
"""Survey_Data_Formatter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EeFMyBRYhb70r7DQe_mJ_LacYofCj_G
"""

import pandas as pd

# Load data
df = pd.read_csv('survey.csv')

# Preview first few rows
df.head()

def normalize_yes_no(val):
    if str(val).strip().lower() in ['yes', 'y']:
        return 'Yes'
    elif str(val).strip().lower() in ['no', 'n']:
        return 'No'
    else:
        return val

# Normalize for all object-type columns
for col in df.select_dtypes(include='object'):
    df[col] = df[col].apply(normalize_yes_no)

# Remove completely empty rows
df.dropna(how='all', inplace=True)

# Remove rows with more than 50% missing values
df.dropna(thresh=len(df.columns) // 2, inplace=True)

# Drop completely empty columns
df.dropna(axis=1, how='all', inplace=True)

# Drop columns with only one unique value
df = df.loc[:, df.nunique() > 1]

# Remove rows where 'Subscribed' column is empty or null
df = df[df['Subscribed'].notna()]
df = df[df['Subscribed'].str.strip() != '']

df.to_csv('cleaned_survey_final.csv', index=False)
print("Cleaned data saved as 'cleaned_survey_final.csv'")

import pandas as pd

# Load the cleaned survey data
df = pd.read_csv('cleaned_survey_final.csv')  # Add .csv extension

# Show first 5 rows
df.head()

import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set(style="whitegrid")

# Load cleaned data
df = pd.read_csv('cleaned_survey_final.csv')

# Plot bar chart for 'Subscribed' column
plt.figure(figsize=(6, 4))
sns.countplot(x='Subscribed', data=df, palette='pastel')
plt.title('Subscription Status Count')
plt.xlabel('Subscribed')
plt.ylabel('Count')
plt.tight_layout()
plt.show()